[package]
name = "file-reader"
version = "0.1.0"
description = "文件读写示例"
authors = ["Your Name"]
edition = "2021"

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 